# Generated by Django 5.2.5 on 2025-08-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
